name: CI

on:
  push:
    # Specify the branch that will trigger the workflow
    branches: [ "main" ]

jobs:
  # Write name of the job as a key
  hello-from-runner:
    # Specify the runner machine
    runs-on: ubuntu-22.04
    steps:
      # Write the step name
      - name: Print Name
        run: |
          echo "Hello from $(whoami)"
